name = "ai-interview-assistant"
pages_build_output_dir = "./dist"
compatibility_date = "2026-04-07"

[[d1_databases]]
binding = "DB"
database_name = "interview-app-db"
database_id = "3278f73c-61d2-48a0-8533-7e01ed5012a5"
